"use strict";
document.addEventListener("DOMContentLoaded",()=>{
 const $=id=>document.getElementById(id), canvas=$("imageCanvas"),ctx=canvas.getContext("2d",{willReadFrequently:true});
 if(!window.ValueLensColor||!window.ValueLensViewport||!ctx){document.body.textContent="ValueLens could not start. Confirm that all JavaScript files are present.";return;}
 const version=window.ValueLensVersion||{version:"1.1.1",buildDate:"2026-07-21"};$("appVersion").textContent=`v${version.version}`;$("footerVersion").textContent=`v${version.version}`;$("buildDate").textContent=`Built ${version.buildDate}`;
 let image=null,point=null,measurement=null;
 const viewport=ValueLensViewport({container:$("canvasContainer"),stage:$("canvasStage"),canvas,onTap:p=>{if(p.x>=0&&p.y>=0&&p.x<canvas.width&&p.y<canvas.height){point=p;measure();}},onChange:s=>{$("zoomLevel").textContent=`${Math.round(s*100)}%`;}});
 $("zoomIn").onclick=viewport.zoomIn;$("zoomOut").onclick=viewport.zoomOut;$("fitImage").onclick=viewport.fit;$("actualSize").onclick=viewport.actual;
 $("imageFile").addEventListener("change",e=>{const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith("image/")){ $("fileName").textContent="Please choose an image file.";return;}const url=URL.createObjectURL(file),img=new Image();$("fileName").textContent=`Loading ${file.name}…`;img.onload=()=>{URL.revokeObjectURL(url);image=img;point=measurement=null;canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;redraw();$("fileName").textContent=`${file.name} — ${canvas.width} × ${canvas.height}`;$("imagePlaceholder").hidden=true;$("canvasContainer").hidden=false;$("viewportToolbar").hidden=false;$("emptyResult").hidden=false;$("measurementResult").hidden=true;requestAnimationFrame(viewport.fit);};img.onerror=()=>{$("fileName").textContent="ValueLens could not open that image.";URL.revokeObjectURL(url);};img.src=url;});
 $("sampleSize").onchange=()=>point&&measure();$("targetValue").oninput=compare;$("targetTolerance").onchange=compare;$("clearTargetButton").onclick=()=>{$("targetValue").value="";compare();};
 function redraw(){if(!image)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(image,0,0);if(point)crosshair(point.x,point.y);}
 function average(cx,cy,size){const half=Math.floor(size/2),left=Math.max(0,cx-half),top=Math.max(0,cy-half),right=Math.min(canvas.width-1,cx+half),bottom=Math.min(canvas.height-1,cy+half),w=right-left+1,h=bottom-top+1,data=ctx.getImageData(left,top,w,h).data;let r=0,g=0,b=0,a=0;for(let i=0;i<data.length;i+=4){const weight=data[i+3]/255;r+=data[i]*weight;g+=data[i+1]*weight;b+=data[i+2]*weight;a+=weight;}return{r:a?Math.round(r/a):0,g:a?Math.round(g/a):0,b:a?Math.round(b/a):0,w,h};}
 function measure(){redraw();const c=average(point.x,point.y,Number($("sampleSize").value)),lab=ValueLensColor.rgbToLab(c.r,c.g,c.b),value=ValueLensColor.labLightnessToRoundedPainterValue(lab.l);measurement={...c,lab,value};display();redraw();}
 function display(){const m=measurement;$("emptyResult").hidden=true;$("measurementResult").hidden=false;$("painterValue").textContent=m.value.toFixed(1);$("labL").textContent=m.lab.l.toFixed(1);$("labA").textContent=signed(m.lab.a);$("labB").textContent=signed(m.lab.b);$("rgbR").textContent=m.r;$("rgbG").textContent=m.g;$("rgbB").textContent=m.b;$("hexValue").textContent=ValueLensColor.rgbToHex(m.r,m.g,m.b);$("sampleDimensions").textContent=`${m.w} × ${m.h}`;$("sampleCoordinates").textContent=`x ${point.x}, y ${point.y}`;$("colorPreview").style.background=ValueLensColor.rgbToCss(m.r,m.g,m.b);compare();}
 function signed(n){const v=ValueLensColor.roundTo(n,1);return `${v>0?"+":""}${v.toFixed(1)}`;}
 function compare(){const box=$("targetComparison"),raw=$("targetValue").value,target=Number(raw),tol=Number($("targetTolerance").value);if(!measurement||raw.trim()===""||target<1||target>10){box.hidden=true;return;}const d=measurement.value-target,ad=Math.abs(d);box.hidden=false;box.className="target-comparison "+(ad<=tol?"good":d>0?"too-light":"too-dark");$("targetMessage").textContent=ad<=tol?`On target: measured ${measurement.value.toFixed(1)}, planned ${target.toFixed(1)}.`:`Too ${d>0?"light":"dark"} by ${ad.toFixed(1)} value ${Math.abs(ad-1)<.05?"step":"steps"}.`;}
 function crosshair(x,y){const radius=ValueLensColor.clamp(Math.min(canvas.width,canvas.height)*.018,8,30),width=ValueLensColor.clamp(Math.min(canvas.width,canvas.height)*.002,2,5);ctx.save();for(const [stroke,w] of [["rgba(0,0,0,.9)",width+2],["rgba(255,255,255,.95)",width]]){ctx.strokeStyle=stroke;ctx.lineWidth=w;ctx.beginPath();ctx.arc(x,y,radius,0,Math.PI*2);ctx.moveTo(x-radius*1.45,y);ctx.lineTo(x-radius*.35,y);ctx.moveTo(x+radius*.35,y);ctx.lineTo(x+radius*1.45,y);ctx.moveTo(x,y-radius*1.45);ctx.lineTo(x,y-radius*.35);ctx.moveTo(x,y+radius*.35);ctx.lineTo(x,y+radius*1.45);ctx.stroke();}ctx.restore();}
});
